Handle load batch inscriptions
openbitdev/OpenBit-Wallet pull request #185
Opened 2024-06-18 03:37 UTC by bluezdot

2024-06-18 03:45 UTC, saltict commented
<!-- NETLIFY DEPLOY COMMENT GENERATED BY ACTIONS_NETLIFY - APP ID SHA256: 8061f7da7ef62e7b3790a5026c234bcf74150583a4b418361852bdc8ff86cafb -->
🚀 Deployed on https://pr-185--papaya-melba-f5c160.netlify.app

2024-06-18 04:42 UTC, nampc1 requested changes

2024-06-18 04:42 UTC, nampc1 commented on packages/extension-base/src/koni/api/nft/index.ts
> +    await Promise.all(this.handlers.map(async (handler) => {
should only trigger the target handler

2024-06-18 04:42 UTC, nampc1 commented on packages/extension-base/src/koni/background/subscription.ts
> +      (address: string) => this.dbService.getAddressTotalNfts([address])
should count nfts by collection info

2024-06-24 10:37 UTC, saltict approved these changes

2024-06-24 10:38 UTC, merged