Refactor the code for sendTransfer in the new workflow
openbitdev/OpenBit-Wallet pull request #236
Opened 2024-07-04 08:11 UTC by Thiendekaco

2024-07-04 08:20 UTC, saltict commented
<!-- NETLIFY DEPLOY COMMENT GENERATED BY ACTIONS_NETLIFY - APP ID SHA256: 8061f7da7ef62e7b3790a5026c234bcf74150583a4b418361852bdc8ff86cafb -->
🚀 Deployed on https://pr-236--papaya-melba-f5c160.netlify.app

2024-07-06 05:00 UTC, S2kael requested changes

2024-07-06 09:33 UTC, S2kael commented on packages/extension-base/src/services/request-service/handler/BitcoinRequestHandler.ts
> +      emitterTransaction.emit('error', { ...eventData, errors: [new TransactionError(BasicTxErrorType.INVALID_PARAMS, (e as Error).message)] });
Add throw error here to break flow

2024-07-06 11:34 UTC, S2kael approved these changes

2024-07-06 11:46 UTC, merged